/**
 * @fileoverview Output Writer for managing task execution outputs
 * @module output-writer
 */

import { mkdir, writeFile, readFile, readdir } from 'fs/promises';
import { join, dirname } from 'path';
import { existsSync } from 'fs';

/**
 * Output Writer class
 */
export class OutputWriter {
  /**
   * @param {string} baseDir - Base output directory
   * @param {string} sessionId - Session ID for this output set
   */
  constructor(baseDir, sessionId) {
    this.baseDir = baseDir;
    this.sessionId = sessionId;
    this.outputDir = join(baseDir, sessionId);
  }

  /**
   * Ensure directory exists
   * @param {string} dir
   * @private
   */
  async ensureDir(dir) {
    if (!existsSync(dir)) {
      await mkdir(dir, { recursive: true });
    }
  }

  /**
   * Initialize output directory structure
   */
  async initialize() {
    await this.ensureDir(join(this.outputDir, 'tasks'));
    await this.ensureDir(join(this.outputDir, 'evaluations'));
    await this.ensureDir(join(this.outputDir, 'artifacts'));
  }

  /**
   * Generate task output filename
   * @param {Object} task
   * @returns {string}
   */
  getTaskFilename(task) {
    const seq = String(task.sequenceNumber).padStart(3, '0');
    const safeId = task.id.replace(/[^a-zA-Z0-9-]/g, '_');
    return `${seq}-${safeId}.md`;
  }

  /**
   * Generate evaluation filename
   * @param {Object} task
   * @returns {string}
   */
  getEvaluationFilename(task) {
    const seq = String(task.sequenceNumber).padStart(3, '0');
    const safeId = task.id.replace(/[^a-zA-Z0-9-]/g, '_');
    return `${seq}-${safeId}-eval.json`;
  }

  /**
   * Write task execution output
   * @param {Object} task
   * @param {Object} executionResult
   * @param {Object} [metadata={}]
   * @returns {Promise<string>} File path
   */
  async writeTaskOutput(task, executionResult, metadata = {}) {
    const filename = this.getTaskFilename(task);
    const filepath = join(this.outputDir, 'tasks', filename);

    const content = this.formatTaskOutput(task, executionResult, metadata);
    
    await this.ensureDir(dirname(filepath));
    await writeFile(filepath, content, 'utf-8');

    return filepath;
  }

  /**
   * Format task output as markdown
   * @param {Object} task
   * @param {Object} result
   * @param {Object} metadata
   * @returns {string}
   * @private
   */
  formatTaskOutput(task, result, metadata) {
    const toolInvocations = result.toolInvocations?.map(inv => `
### ${inv.toolName}

**Parameters:**

\`\`\`json
${JSON.stringify(inv.parameters, null, 2)}
\`\`\`

**Result:**

${inv.result}

**Status:** ${inv.success ? 'Success' : 'Failed'}
**Duration:** ${inv.durationMs || 'N/A'}ms
`).join('\n') || 'No tool invocations recorded';

    return `# Task Execution: ${task.title}

## Task Information

- **Task ID:** ${task.id}
- **Goal ID:** ${task.goalId}
- **Sequence:** ${task.sequenceNumber}
- **Executed At:** ${metadata.executedAt || new Date().toISOString()}
- **Duration:** ${metadata.durationMs || 'N/A'}ms

## Task Description

${task.description}

## Tool Binding

- **Tool:** ${typeof task.tool === 'object' ? (task.tool?.toolName || task.tool?.name || '(none)') : (task.tool || '(none)')}
- **Action:** ${task.tool?.command?.action || 'execute'}
- **Parameters:**

\`\`\`json
${JSON.stringify(task.tool?.command?.parameters || {}, null, 2)}
\`\`\`

- **Expected Output:** ${task.tool?.command?.expectedOutput || '(not specified)'}

## Execution Output

${result.output || 'No output captured'}

## Tool Invocations

${toolInvocations}

## Reasoning

${result.reasoning || 'No reasoning provided'}

---

*Generated by Action Plan Service v1.0.0*
`;
  }

  /**
   * Write evaluation result
   * @param {Object} task
   * @param {Object} evaluation
   * @returns {Promise<string>} File path
   */
  async writeEvaluation(task, evaluation) {
    const filename = this.getEvaluationFilename(task);
    const filepath = join(this.outputDir, 'evaluations', filename);

    const content = JSON.stringify({
      taskId: task.id,
      evaluatedAt: new Date().toISOString(),
      ...evaluation
    }, null, 2);

    await this.ensureDir(dirname(filepath));
    await writeFile(filepath, content, 'utf-8');

    return filepath;
  }

  /**
   * Write execution log
   * @param {Object} logData
   * @returns {Promise<string>}
   */
  async writeExecutionLog(logData) {
    const filepath = join(this.outputDir, 'execution-log.json');
    
    await this.ensureDir(dirname(filepath));
    await writeFile(filepath, JSON.stringify(logData, null, 2), 'utf-8');

    return filepath;
  }

  /**
   * Write summary document
   * @param {Object} summaryData
   * @returns {Promise<string>}
   */
  async writeSummary(summaryData) {
    const filepath = join(this.outputDir, 'summary.md');
    
    const content = this.formatSummary(summaryData);
    
    await this.ensureDir(dirname(filepath));
    await writeFile(filepath, content, 'utf-8');

    return filepath;
  }

  /**
   * Format summary as markdown
   * @param {Object} data
   * @returns {string}
   * @private
   */
  formatSummary(data) {
    const taskRows = data.tasks?.map(t => {
      const status = t.state === 'completed' ? '[+] Success' : '[x] Failed';
      return `| ${t.sequenceNumber} | ${t.title} | ${t.goalId} | ${status} | ${t.executionTimeMs || 'N/A'}ms |`;
    }).join('\n') || 'No tasks';

    const issues = data.issues?.map(i => `- ${i}`).join('\n') || 'None';
    const artifacts = data.artifacts?.length > 0
      ? data.artifacts.map(a => {
          if (typeof a === 'string') return `- ${a}`;
          const size = a.size ? ` (${a.size} bytes)` : '';
          const tool = a.tool ? ` [${a.tool}]` : '';
          return `- \`${a.path}\`${size}${tool}`;
        }).join('\n')
      : 'None';

    return `# Execution Summary

## Session Information

- **Session ID:** ${data.sessionId}
- **Started:** ${data.startedAt}
- **Completed:** ${data.completedAt}
- **Duration:** ${data.totalDurationMs || 'N/A'}ms
- **Final Status:** ${data.finalStatus}

## Metrics

| Metric | Value |
|--------|-------|
| Total Tasks | ${data.totalTasks} |
| Completed | ${data.completedCount} |
| Failed | ${data.failedCount} |
| Total Execution Time | ${data.totalExecutionTimeMs || 0}ms |
| Total Tokens Used | ${data.totalTokens || 0} |

## Task Results

| # | Task | Goal | Status | Duration |
|---|------|------|--------|----------|
${taskRows}

## Issues Encountered

${issues}

## Files Generated

${artifacts}

---

*Generated by Action Plan Service v1.0.0*
`;
  }

  /**
   * Copy artifact file
   * @param {string} sourcePath
   * @param {string} filename
   * @returns {Promise<string>}
   */
  async copyArtifact(sourcePath, filename) {
    const destPath = join(this.outputDir, 'artifacts', filename);
    
    await this.ensureDir(dirname(destPath));
    
    const content = await readFile(sourcePath);
    await writeFile(destPath, content);

    return destPath;
  }

  /**
   * Get output directory path
   * @returns {string}
   */
  getOutputDir() {
    return this.outputDir;
  }

  /**
   * List all output files
   * @returns {Promise<Object>}
   */
  async listOutputs() {
    const result = {
      tasks: [],
      evaluations: [],
      artifacts: []
    };

    try {
      const tasksDir = join(this.outputDir, 'tasks');
      if (existsSync(tasksDir)) {
        result.tasks = await readdir(tasksDir);
      }

      const evalsDir = join(this.outputDir, 'evaluations');
      if (existsSync(evalsDir)) {
        result.evaluations = await readdir(evalsDir);
      }

      const artifactsDir = join(this.outputDir, 'artifacts');
      if (existsSync(artifactsDir)) {
        result.artifacts = await readdir(artifactsDir);
      }
    } catch (err) {
      // Ignore errors
    }

    return result;
  }
}

export default OutputWriter;
